[book]
authors = ["Aaron Erhardt"]
language = "en"
src = "src"
title = "GUI development with Relm4"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/Relm4/book"
edit-url-template = "https://github.com/Relm4/book/edit/main/{path}"
git-repository-icon = "fa-github"
