[package]
name = "book-examples"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
publish = false
version = "0.0.0"

readme = "README.md"
license = "MIT"

keywords = ["gui", "gtk", "gtk4"]
categories = ["gui"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8.5"
relm4 = { git = "https://github.com/Relm4/Relm4", features = ["all"] }
relm4-components = { git = "https://github.com/Relm4/Relm4" }
tokio = { version = "1.9", features = ["rt", "macros", "time", "rt-multi-thread", "sync"] }
tracker = "0.1.1"
