[package]
name = "libadwaita-examples"
version = "0.0.0"
publish = false
edition = "2024"
rust-version = "1.92"

[dev-dependencies]
relm4 = { workspace = true, features = ["libadwaita"] }

[[example]]
name = "simple_manual"
path = "simple_manual.rs"
